# Deployment workflow (optional - for when you're ready to deploy)
name: Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  test-before-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        enable-cache: true
    
    - name: Set up Python
      run: uv python install 3.13
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run full test suite
      run: uv run pytest tests/ -v --cov=src --cov-report=term
  
  # Uncomment and configure when ready to deploy
  # deploy:
  #   needs: test-before-deploy
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   
  #   - name: Deploy to Render (example)
  #     run: |
  #       echo "Deploying to production..."
  #       # Add your deployment steps here
  #       # For example, triggering a Render deployment webhook
  #       curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
  #   
  #   - name: Create GitHub Release (for tags)
  #     if: startsWith(github.ref, 'refs/tags/v')
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: Release ${{ github.ref }}
  #       body: |
  #         Changes in this release:
  #         - See commit history for details
  #       draft: false
  #       prerelease: false
