name: Dependency Updates

on:
  schedule:
    # Check for dependency updates weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        enable-cache: true
    
    - name: Set up Python
      run: uv python install 3.13
    
    - name: Update dependencies
      run: |
        echo "Current uv.lock:"
        head -20 uv.lock || echo "No uv.lock found"
        echo ""
        echo "Updating dependencies..."
        uv sync --upgrade
        echo ""
        echo "Updated uv.lock:"
        head -20 uv.lock || echo "No uv.lock found"
    
    - name: Run tests with updated dependencies
      run: uv run pytest tests/ -v --tb=short
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🔄 Update dependencies"
        body: |
          This is an automated dependency update.
          
          ## Changes
          - Updated all dependencies to their latest compatible versions
          - All tests are passing with the new dependencies
          
          ## Testing
          - [x] All existing tests pass
          - [x] No breaking changes detected
          
          Please review the changes and merge if everything looks good.
        branch: automated-dependency-update
        delete-branch: true
